name: Responsible AI Monitoring

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run audit script
        run: python scripts/train_and_audit.py

      - name: Upload audit artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fairness-report
          path: artifacts/fairness_audit.csv
          if-no-files-found: warn
          retention-days: 30
