name: Responsible AI Monitoring

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install pandas scikit-learn numpy shap fairlearn
          fi

      - name: Run audit
        run: |
          python scripts/run_audit.py

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: rai-report
          path: |
            reports/**
            *.html
          if-no-files-found: warn
          retention-days: 30
